        <footer class="w3-container w3-dark-gray">
	    <p class="w3-left">
Er noe uklart? Ta kontakt med: Navn Navnsen<br />
<a href="mailto:navn.navnsen@ntnu.no">navn.navnsen@ntnu.no</a>
</p>
<!--
	    <div class="w3-center">
                <img src="assets/trondheim.svg" height="70px" class="w3-margin">
            	<img src="assets/gjovik.svg" height="70px" class="w3-margin">
                <img src="assets/alesund.svg" height="70px" class="w3-margin">
	    </div>
-->
            <img src="assets/inst_for_fysikk_hoeyde_white.svg" height="50px" class="w3-right w3-margin">
        </footer>
    </body>
</html>
