<?php $activePage = "forberedelse.phtml" ?>
<?php include 'head.phtml'; ?>
<div class="w3-container w3-blue w3-center w3-card">
    <h1>Forberedelse til lab!</h1>

    <div class="crop_frame">
	<img src="assets/tracker.jpg" class="w3-card">
    </div>
</div>

<!-- <section class="w3-container w3-panel w3-sand w3-margin w3-padding-32 w3-leftbar"> -->
<section class="narrow">
    <h2>Før lab må du laste ned programmet Tracker</h2>
    <p>
	Tracker kan du laste ned ved å følge denne (eksterne) lenken: <a href="https://www.compadre.org/osp/items/detail.cfm?ID=7365" target="_blank">Tracker</a>.<br />
	<ul>
	    <li>En veldig rask (2m30s) innføring i programmet, finner du på YouTube <a href="https://youtu.be/n4Eqy60yYUY" target="_blank">her</a>.</li>
	    <li>En ganske rask (15m) innføring i programmet, finner du på YouTube <a href="https://youtu.be/La3H7JywgX0" target="_blank">her</a>.</li>
	</ul>
	Begge videoene er laget utvikleren av Tracker.
    </p>
</section>

<section class="w3-container w3-panel w3-sand w3-margin w3-padding-32 w3-leftbar">
    <h2><i class="material-icons w3-xxlarge">announcement</i> Les gjennom labheftet <i>før</i> labben</h2>
</section>

<?php
$resources = array(
    "Labhefte" => ["Labheftet beskriver hva du skal gjøre på labben", "dummy_link"],
    "Video" => ["Kort (2m30s) YouTube-video som beskriver bruken av Tracker", "https://youtu.be/n4Eqy60yYUY"],
    "Video II" => ["Ganske kort (15m) YouTube-video som beskriver bruken av Tracker", "https://youtu.be/La3H7JywgX0"],
    "Video III" => ["Video som raskt viser eksperimentet dere skal gjøre", "assets/LabVideoHome.mp4"]
);
include('resources.php');
?>
<?php include 'footer.phtml'; ?>
