<?php $activePage = "forberedelse.phtml" ?>
<?php include 'head.phtml'; ?>
<div class="w3-container w3-blue w3-center w3-card">
    <h1>Forberedelse til lab!</h1>

    <div class="crop_frame">
	<img src="assets/tracker.jpg" class="w3-card">
    </div>
</div>

<!-- <section class="w3-container w3-panel w3-sand w3-margin w3-padding-32 w3-leftbar"> -->
<section class="narrow w3-padding">
    <h2>Før lab:</h2>
	<ul class="w3-ul">
	<li>Last ned <a href="https://www.compadre.org/osp/items/detail.cfm?ID=7365">Tracker</a></li>
	<li>Se gjennom ressursene under, det er labheftet samt tre korte videoer</li>
	</ul>
</section>

<?php
$resources = array(
    "Labhefte" => ["Labheftet beskriver hva du skal gjøre på labben", "dummy_link"],
    "Video" => ["Kort (2m30s) YouTube-video som beskriver bruken av Tracker", "https://youtu.be/n4Eqy60yYUY"],
    "Video II" => ["Ganske kort (15m) YouTube-video som beskriver bruken av Tracker", "https://youtu.be/La3H7JywgX0"],
    "Video III" => ["Video som raskt viser eksperimentet dere skal gjøre", "assets/LabVideoHome.mp4"]
);
include('resources.php');
?>
<?php include 'footer.phtml'; ?>
