<!-- Expects $activePage to be set, which is one of the keys in $urls defined in this document. -->
<nav class="w3-bar w3-dark-gray">
    <?php
    $urls = array(
    'Home' => '/',
    'Forberedelser' => 'forberedelser.html',
    'På labben' => 'lab.html',
    'Rapport' => 'rapport.html'
    );

    foreach ($urls as $name=>$url) {
    print '<a href="index.html" class="w3-bar-item w3-button w3-mobile'(($activePage == $name) ? 'w3-blue' : '').'">Home</a>';
    }
    ?>
    <a href="#" class="w3-bar-item w3-button w3-mobile w3-right">Hjelp</a>
</nav>
