<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="HandheldFriendly" content="true" />
	<!--<meta name="MobileOptimized" content="320" />-->
	<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, width=device-width, user-scalable=no" />
        <!--<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> -->
	<link rel="stylesheet" href="w3.css">
        <link rel="stylesheet" href="style.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<title>Fysikklab</title>
    </head>
    <body>
    <?php include 'navbar.phtml'; ?>
