<?php $activePage = "lab.phtml"; ?>
<?php include 'head.phtml'; ?>

<div class="w3-container w3-blue w3-center w3-card">
<h1>På lab</h1>
</div>

<section class="narrow w3-padding">
    <h2>Gjøremål:</h2>
        <ul class="w3-ul">
        <li>Sett opp eksperimentet slik det er beskrevet i labheftet</li>
        <li>Gjennomfør fem måleserier med hvert legeme</li>
        </ul>
</section>


<section class="w3-container w3-panel w3-sand w3-padding-32 w3-margin-top w3-leftbar narrow">
<h2>Hvor?</h2>

<section class="w3-border">
<script>
function updateLocation() {
	let radios = document.getElementsByName("location");
	/* Yes, I know this is ugly */
	for (let radio of radios) {
		if (radio.checked) {
			radio.labels[0].classList.add("w3-dark-gray");
			radio.labels[1].classList.remove("w3-hide");
		} else {
			radio.labels[0].classList.remove("w3-dark-gray");
			radio.labels[1].classList.add("w3-hide");
		}
	}	
}
</script>
<div class="w3-bar w3-light-gray" onchange="updateLocation()">
<label class="w3-dark-gray">
<input class="w3-hide" type="radio" name="location" id="trondheim"> 
<div class="w3-bar-item w3-button">Trondheim</div>
</label>

<label>
<input class="w3-hide" type="radio" name="location" id="gjovik">
<div class="w3-bar-item w3-button">Gjøvik</div>
</label>

<label>
<input class="w3-hide" type="radio" name="location" id="alesund">
<div class="w3-bar-item w3-button">Ålesund</div>
</label>
</div>

<div class="w3-dark-gray w3-padding">
<label for="trondheim"> 
<p>Rom C3-101 i Realfagsbygget.</p>
<a href="https://bit.ly/3abMjcW">Åpne i MazeMap</a>
<!-- <iframe width="600" height="420" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://use.mazemap.com/embed.html#v=1&zlevel=3&center=10.406247,63.415877&zoom=17.7&sharepoitype=poi&sharepoi=404271&campusid=1&utm_medium=iframe" style="border: 1px solid grey" allow="geolocation"></iframe><br/><small><a href="https://www.mazemap.com/">Map by MazeMap</a></small>
-->
</label>


<label for="gjovik" class="w3-hide">
<p>Rom C3-1 i Kunnskapshuset.</p>
<a href="https://bit.ly/3adjIEn">Åpne i MazeMap</a>
<!-- <iframe width="600" height="420" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://use.mazemap.com/embed.html#v=1&zlevel=3&center=10.676408,60.789054&zoom=17.8&campusid=55&sharepoitype=poi&sharepoi=1137452&utm_medium=iframe" style="border: 1px solid grey" allow="geolocation"></iframe><br/><small><a href="https://www.mazemap.com/">Map by MazeMap</a></small>
-->
</label>


<label for="alesund" class="w3-hide">
<p>Rom C301 i Finneths bygg.</p>
<a href="https://bit.ly/3oX6ob0">Åpne i MazeMap</a>
<!-- <iframe width="600" height="420" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://use.mazemap.com/embed.html#v=1&zlevel=3&center=6.235597,62.472048&zoom=18.9&campusid=91&sharepoitype=poi&sharepoi=1000290547&utm_medium=iframe" style="border: 1px solid grey" allow="geolocation"></iframe><br/><small><a href="https://www.mazemap.com/">Map by MazeMap</a></small>
-->
</label>
</div>
</section>
</section>

<?php
$resources = array(
    "Labhefte" => ["Labheftet beskriver hva du skal gjøre på labben", "dummy_link"],
    "Oppsett" => ["Video som raskt viser eksperimentet dere skal gjøre", "assets/LabVideoHome.mp4"]
);
include('resources.php');
?>
<?php include 'footer.phtml'; ?>

