<?php include 'head.phtml'; ?>
<div class="w3-container w3-blue w3-center w3-card">
    <h1>Forberedelse til lab!</h1>

    <div class="crop_frame">
	<img src="assets/tracker.jpg" class="w3-card">
    </div>
</div>
<section class="w3-container narrow w3-margin-top">
<video src="assets/LabVideo.mp4" controls width="100%" class="w3-card"
<a href="assets/LabVideo.mp4">Last ned video</a>
</video>
</section>
<?php include 'footer.phtml'; ?>
